const dogsData = {
    names: [
        "Olivia",
        "Liam",
        "Emma",
        "Noah",
        "Amelia",
        "Oliver",
        "Ava",
        "Elijah",
        "Sophia",
        "Mateo",
        "Isabella",
        "Lucas",
        "Luna",
        "Levi",
        "Mia",
        "Asher",
        "Charlotte",
        "Leo",
        "Evelyn",
        "James",
        "Harper",
        "Luca",
        "Scarlett",
        "Grayson",
        "Nova",
        "Ezra",
        "Aurora",
        "Ethan",
        "Ella",
        "Wyatt",
        "Aria",
        "Aiden",
        "Mila",
        "Sebastian",
        "Gianna",
        "Benjamin",
        "Ellie",
        "Henry",
        "Sofia",
        "Mason",
        "Willow",
        "Hudson",
        "Layla",
        "Jack",
        "Violet",
        "Owen",
        "Camila",
        "Alexander",
        "Avery",
        "Daniel",
        "Hazel",
        "Maverick",
        "Chloe",
        "Kai",
        "Elena",
        "Gabriel",
        "Eliana",
        "Carter",
        "Penelope",
        "William",
        "Paisley",
        "Logan",
        "Eleanor",
        "Michael",
        "Elizabeth",
        "Samuel",
        "Ivy",
        "Muhammad",
        "Isla",
        "Jayden",
        "Riley",
        "Ezekiel",
        "Abigail",
        "Lincoln",
        "Nora",
        "Luke",
        "Grace",
        "Waylon",
        "Stella",
        "Theo",
        "Zoey",
        "Josiah",
        "Emily",
        "Elias",
        "Everly",
        "Jacob",
        "Emilia",
        "David",
        "Kinsley",
        "Julian",
        "Athena",
        "Jaxon",
        "Leilani",
        "Theodore",
        "Maya",
        "Nathan",
        "Delilah",
        "Matthew"
    ],

    bio: [
        "Hi, How are you ~",
        "I like chewing gums",
        "I am at my best running in the park",
        "Heyyyy , I can not wait to meet you ~",
        "I like having lots of friends",
        "My favourite food is ham, which is yours?",
        "Have you tried dancing? Me neither ~",
        "I hate barking at the wrong tree !",
        "I love going to the haridressers!",
        "Do you like my name ?",
        "I am always kind to other puppies ~",
        "Hiya, nice to meet you ~",
        "My favourite country is Spain",
        "My favourite city is Paris, which is yours?",
        "I really enjoy myself when running in the rain",
        "I am really scared of mice, what about you?",
        "I adore Christmas as I get a lot of presents",
        "I have once won a beaut contest- true or false?",
        "Hiya - lovely to see  you here!",
        "My favourite food is cheese",
        "I cant wait to meet you!",
        "My favourite music is Rock",
        "Hiya- My favourite pastime is sleeping",
        "I wake up early in the morning",
        "I  love parties and baloons",
        "Hey-hope you have a good day",
        "There is nothing better than a nap!",
        "I can not wait for Christmas!",
        "Hey- I will be your best friend",
        "My favourite colour is yellow",
        "My favourite season is winter",
        "I love the blue skies",
        "My favourite colour is black",
        "My favourite colour is purple ?",
        "I love the calm evenings",
        "My favourite colour is black",
        "My favourite colour is pink",
        "Hey- how you doing?",
        "I love rollercoasters!",
        "My best friends are cats!",
        "I love reading books!",
        "My favourite season is autumn",
        "Hiya- how are you today?",
        "I love being happy",
        "I dont like being alone",
        "Hey- I like snow",
        "I love being spoilt",
        "I hate children lol",
        "My favourite sport is rugby",
        "My favourite sport is basketball",
        "My favourite music is Dance",
        "Hiya- beatiful day, right?",
        "I hate the sandy beaches!",
        "Hey -I like thunderstorms",
        "You will not see me on a  motorbike",
        "My favourite drink is orange juice",
        "I adore the sandy beaches!",
        "I love the beach!",
        "My favourite season is spring",
        "Hey-what's up?",
        "You will not see me in the rain! ?",
        "Hey- I like rain",
        "I adore my name - what about you?",
        "I can not sleep in the day!",
        "My favourite music is Classic music",
        " Hey- What makes you happy?",
        "My favourite food is spaghetti",
        "I hate muddy puddles!",
        "I adore muddy puddles!",
        "My favourite season is summer",
        "You will not see me on a cruise",
        "My favourite drink is apple juice",
        "Hey- I like rocks"
    ]
}

export default dogsData;